### ISSUE TITLE
Replace human-readable text with i18n keys

### ISSUE THREAD

**Issue by jelveh** [HeyPuter/puter#663]
For translation purposes, we need to replace all human-readable text in the UI components with `i18n(key)` calls. This will allow for easier localization in the future.

## Tasks
- [ ] Identify all human-readable text in files located under `./src/gui/src/UI`
- [ ] Replace each instance of human-readable text with `i18n(key)`
- [ ] Add corresponding translations for each key in `./src/gui/src/i18n/translations/en.js`

## Implementation Details
1. Go through each file in `./src/gui/src/UI`
2. For each human-readable string found:
   - Create a unique, descriptive key for the string
   - Replace the string with `i18n(key)`
   - Add the key-value pair to `./src/gui/src/i18n/translations/en.js`

## Example

Before:
```javascript
<button>Submit</button>
```

After:
```javascript
<button>{i18n('submit')}</button>
```
In `./src/gui/src/i18n/translations/en.js`:

```javascript
const en = {
    name: "English",
    english_name: "English",
    code: "en",
    dictionary: {
        // ... existing translations
        'submit_button_text': 'Submit',
        // ... existing translations
    }
}
```

## Additional Notes

- Ensure keys are descriptive and follow a consistent naming convention
- Be cautious with dynamic text or text that includes variables
- Consider context when creating keys to avoid potential conflicts

## Definition of Done

- All human-readable text in files under `./src/gui/src/UI` is replaced with `i18n(key)` calls.
- All new keys are added to `./src/gui/src/i18n/translations/en.js` with correct English translations.
- The application builds without errors and all UI elements display correctly.

**Comment by ADTmux** [comment]
hey can I work on this?

**Comment by jelveh** [comment]
Of course! Assigned ✌️

Let me know if you need help.

**Comment by NFFY88** [comment]
Hi! If you need help translating new keys into Russian, call me.

**Comment by Schlipe** [comment]
Hey, mind if I give a go?

**Comment by jelveh** [comment]
> Hey, mind if I give a go?

This issue is already assigned. Let me double-check quickly to see if they're working on it. 

Hey @ADTmux, are you still working on this issue?

**Comment by jelveh** [comment]
@ADTmux just a quick follow-up, are you still working on this? I think @Schlipe is interested if you don't have time to finish it.

**Comment by jelveh** [comment]
@Schlipe are you still interested in picking this up? I can assign it to you.

**Comment by Schlipe** [comment]
> @Schlipe are you still interested in picking this up? I can assign it to you.

Yes, u may assign

**Comment by jelveh** [comment]
Thank you @Schlipe ! Assigned. 
Let me know if you need any help :)

**Comment by nbgslv** [comment]
Hey. LMK if any help needed. I can contribute.

**Comment by Anant1107** [comment]
Hi. Is this issue still open ? I would love to work on this.

**Comment by jelveh** [comment]
Yes, it's still open! Assigned :)
Let me know if you need help.

**Comment by meher745** [comment]
Can I give it a try? @jelveh

**Comment by jelveh** [comment]
Hi @meher745, thanks for your interest in contributing to Puter. This issue is already assigned to @Anant1107. I'd be happy to assign another issue to you if you're interested.

**Comment by meher745** [comment]
HI @jelveh , I would love to work on another issue. Pease assign it to me.

**Comment by karan1205** [comment]
Hi @jelveh Is this issue still open? Can I take it?
