### ISSUE TITLE
Translate README.md from English to Dutch

### ISSUE THREAD

**Issue by jelveh** [HeyPuter/puter#736]
We need to create a Dutch version of our README to make our project more accessible to Dutch-speaking users and contributors.

### Task Description

- Translate the content of `./doc/i18n/README.en.md` to Dutch
- Create a new file `./doc/i18n/README.nl.md` with the translated content
- Ensure the format and styling of the original English README is preserved exactly in the Dutch version

### Steps

1. Copy the existing `README.en.md` file to create `README.nl.md` in the same directory (`./doc/i18n/`)
2. Translate all text content from English to Dutch, including:
   - Headings
   - Paragraphs
   - Lists
   - Code comments (if any)
   - Any other textual content
3. Preserve all markdown formatting, including:
   - Heading levels
   - Bold and italic text
   - Links
   - Code blocks
   - Tables
   - Images
4. Ensure all links and references remain functional in the Dutch version
5. Update any language-specific content (e.g., language badges) to reflect Dutch instead of English

### Additional Considerations

- Maintain consistent terminology throughout the translation
- Pay attention to technical terms that may have specific translations or may need to remain in English
- If there are any culture-specific examples or references, consider adapting them for a Dutch-speaking audience if appropriate

### Definition of Done

- [ ] `README.nl.md` file created in `./doc/i18n/` directory
- [ ] All content accurately translated to Dutch
- [ ] Format and styling match the original English version exactly
- [ ] All links and references are functional
- [ ] Translation reviewed by a native Dutch speaker (if possible)
- [ ] Update project documentation or configuration to include the new Dutch README (if necessary)

### Resources

- Original English README: `./doc/i18n/README.en.md`
- [GitHub Markdown Guide](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) for reference on markdown syntax

**Comment by bibekp-dev** [comment]
can you assign this to me ? @jelveh

**Comment by ruthwikchikoti** [comment]
@jelveh  can i work on this ?

**Comment by ruthwikchikoti** [comment]
please take a look #770

**Comment by Valeria-D-23** [comment]
Hello, can I give it a go?

**Comment by jelveh** [comment]
@Valeria-D-23 absolutely! go for it :)

**Comment by Chirag076** [comment]
is it possible to be assigned to this issue?

**Comment by jelveh** [comment]
Hi @Chirag076! Sure, go for it.

**Comment by Chirag076** [comment]
@jelveh i think it is already been done i can able to see the README.nl.md in that

**Comment by jelveh** [comment]
Ahhh! You're right, this was mistakenly not closed. Sorry about that. Let me know if there is another issue you want to work one :)
