### ISSUE TITLE
To-Do List example not functioning

### ISSUE THREAD

**Issue by salsina** [HeyPuter/puter#768]
**Issue Description**
The todo list is not displayed 
**Steps to Reproduce**
1. Open the playground and the todo list example https://docs.puter.com/playground/index.html?example=app-todo&autorun=1
2. Run
3. Add a task
**Expected & Actual Behavior**
Expected: The todo list should be displayed
Actual: Nothing is displayed
**Addition Information or Screenshots (if applicable)**
Chrome Version 128.0.6613.138 (Official Build) (64-bit) - Windows 10
**Deployment**
- [ ] Production (puter.com)
- [ ] Development (`npm run start`)
- [ ] Docker (via `docker run`)
- [ ] Docker (via `docker-compose`)

**Puter version (if accessible)**
2.4.1

**Comment by KernelDeimos** [comment]
Hello, this should be working now - thanks for reporting this!
